version: "1.0"

services:
  db:
    image: postgres:13
    container_name: task_db
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - task_service_data:/var/lib/postgresql/data

  app:
    image: task-service:latest
    container_name: task-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_db:5432/testDB
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

volumes:
  task_service_data: