# Use the official OpenJDK base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file into the container
COPY build/libs/task-service-0.0.1-SNAPSHOT.jar task-service.jar

# Define the entry point for the container
ENTRYPOINT ["java", "-jar", "task-service.jar"]

# Expose the application port (optional, for documentation purposes)
EXPOSE 8080
