spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/testDB
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always