version: "1.0"

services:
  db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - user_service_data:/var/lib/postgresql/data


volumes:
  user_service_data: